language: python
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

notifications:
  email: false

services:
  - redis-server

install:
  - make
  - make install
  - bin/pip3 install python-coveralls

script:
  - PYTHONPATH=$PWD:$PYTHONPATH make test
  - PYTHONPATH=$PWD:$PYTHONPATH make integration-test

after_success:
  - bin/coveralls
