language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email: false

services:
  - redis-server

install:
  - make
  - bin/buildout

script:
  - PYTHONPATH=$PWD:$PYTHONPATH make all-tests

after_success:
  - coveralls
