language: python
python:
  - "2.6"
  - "2.7"

notifications:
  email: false

services:
  - redis-server

install:
  - make
  - bin/buildout
  - bin/pip install python-coveralls

script:
  - PYTHONPATH=$PWD:$PYTHONPATH make test
  - PYTHONPATH=$PWD:$PYTHONPATH make integration-test

after_success:
  - bin/coveralls
